Adding all possible imports to find out if that's causing the errors
/project/src/org/apache/cordova/plugin/BT77RfidReader.java:115: error:
<identifier> expected
fReader.setAccessible(true);
^
/project/src/org/apache/cordova/plugin/BT77RfidReader.java:115: error:
illegal start of type
fReader.setAccessible(true);
^
/project/src/org/apache/cordova/plugin/BT77RfidReader.java:116: error:
<identifier> expected
uhfreader = fReader.get(this.reader);